<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SolSystem.Core</RootNamespace>
    <AssemblyName>SolSystem.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SolSystem.Core.Tests" />
    <InternalsVisibleTo Include="SolSystem.Spike" />
    <InternalsVisibleTo Include="SolSystem.Probe" />
    <InternalsVisibleTo Include="SolSystem.Client" />
  </ItemGroup>

</Project>
